# Generated by Django 4.2.3 on 2023-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0006_breadingredient_expire_at_breadingredient_expired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breadpage",
            name="introduction_2",
            field=models.TextField(blank=True, help_text="Text to describe the page"),
        ),
    ]
